# Generated by Django 4.0 on 2022-01-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text2',
        ),
        migrations.AddField(
            model_name='post',
            name='ano',
            field=models.CharField(default='Some String', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='duracao',
            field=models.CharField(default='Some String', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Some String', max_length=200),
        ),
    ]
