# Generated by Django 4.0 on 2022-01-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_remove_post_text_remove_post_text2_post_ano_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='post',
            name='descricao',
            field=models.TextField(default='Some String'),
        ),
        migrations.AddField(
            model_name='post',
            name='genero',
            field=models.CharField(default='Some String', max_length=200),
        ),
    ]
