# Generated by Django 4.0 on 2022-01-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_rename_title_post_titulo_post_descricao_post_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ano',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='duracao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='genero',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
