# Generated by Django 4.0 on 2022-01-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0004_alter_post_ano_alter_post_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='texto',
        ),
    ]
