# Generated by Django 4.0 on 2022-01-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0005_rename_author_comment_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
