# Generated by Django 4.0 on 2022-02-01 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0009_alter_postlike_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
    ]
